In [1]:
import pandas as pd

# read the data set

In [2]:
movies = pd.read_csv(r'C:\Users\sheet\Desktop\Full Stack Data Science\Kaggle_Panda\movie.csv')

In [3]:
movies.shape

(27278, 3)

In [4]:
ratings = pd.read_csv(r'C:\Users\sheet\Desktop\Full Stack Data Science\Kaggle_Panda\rating.csv')

In [5]:
ratings.shape

(20000263, 4)

In [6]:
tags = pd.read_csv(r'C:\Users\sheet\Desktop\Full Stack Data Science\Kaggle_Panda\tag.csv')

In [7]:
tags.shape

(465564, 4)

# Data Analysis

In [8]:
print(movies.columns)
print(ratings.columns)
print(tags.columns)

Index(['movieId', 'title', 'genres'], dtype='str')
Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='str')
Index(['userId', 'movieId', 'tag', 'timestamp'], dtype='str')

# For cureent Analysis we will remove timestamp

In [9]:
del ratings['timestamp']
del tags['timestamp']

In [10]:
print(movies.columns)
print(ratings.columns)
print(tags.columns)

Index(['movieId', 'title', 'genres'], dtype='str')
Index(['userId', 'movieId', 'rating'], dtype='str')
Index(['userId', 'movieId', 'tag'], dtype='str')

# Data Structures

In [11]:
tags.head(2)

   userId  movieId          tag
0      18     4141  Mark Waters
1      65      208    dark hero

In [16]:
row_0 = tags.iloc[0] #iloc means integer location
row_0

userId              18
movieId           4141
tag        Mark Waters
Name: 0, dtype: object

In [17]:
row_1 = tags.iloc[1] 
row_1

userId            65
movieId          208
tag        dark hero
Name: 1, dtype: object

In [18]:
print(row_1)

userId            65
movieId          208
tag        dark hero
Name: 1, dtype: object

In [19]:
row_0.index

Index(['userId', 'movieId', 'tag'], dtype='str')

In [21]:
row_1['userId']

np.int64(65)

In [22]:
'rating' in row_0

False

In [25]:
tags.head(2)

   userId  movieId          tag
0      18     4141  Mark Waters
1      65      208    dark hero

In [26]:
print(row_1)

userId            65
movieId          208
tag        dark hero
Name: 1, dtype: object

In [28]:
row_1.name

1

In [29]:
row_0 = row_0.rename('firstRow')
row_0.name

'firstRow'

In [30]:
print(row_0)

userId              18
movieId           4141
tag        Mark Waters
Name: firstRow, dtype: object

In [32]:
row_0 = row_0.rename(1)
row_0.name

1

In [33]:
tags.head(7)

   userId  movieId               tag
0      18     4141       Mark Waters
1      65      208         dark hero
2      65      353         dark hero
3      65      521     noir thriller
4      65      592         dark hero
5      65      668         bollywood
6      65      898  screwball comedy

In [34]:
movies.index

RangeIndex(start=0, stop=27278, step=1)

In [35]:
row_3 = movies.iloc[3] 
row_3

movieId                           4
title      Waiting to Exhale (1995)
genres         Comedy|Drama|Romance
Name: 3, dtype: object

In [36]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [37]:
movies.iloc[ [0,11,111] ]

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
111,113,Before and After (1996),Drama|Mystery

In [38]:
ratings.iloc[ [0,11,111] ]

     userId  movieId  rating
0         1        2     3.5
11        1      296     4.0
111       1     3996     4.0

In [39]:
ratings['rating'].describe()

count    2.000026e+07
mean     3.525529e+00
std      1.051989e+00
min      5.000000e-01
25%      3.000000e+00
50%      3.500000e+00
75%      4.000000e+00
max      5.000000e+00
Name: rating, dtype: float64

In [44]:
ratings['rating'].mean()

np.float64(3.5255285642993797)

In [45]:
ratings.describe()

             userId       movieId        rating
count  2.000026e+07  2.000026e+07  2.000026e+07
mean   6.904587e+04  9.041567e+03  3.525529e+00
std    4.003863e+04  1.978948e+04  1.051989e+00
min    1.000000e+00  1.000000e+00  5.000000e-01
25%    3.439500e+04  9.020000e+02  3.000000e+00
50%    6.914100e+04  2.167000e+03  3.500000e+00
75%    1.036370e+05  4.770000e+03  4.000000e+00
max    1.384930e+05  1.312620e+05  5.000000e+00

In [46]:
ratings['rating'].min()

np.float64(0.5)

In [47]:
ratings['rating'].max()

np.float64(5.0)

In [48]:
ratings['rating'].std()

np.float64(1.0519889192942418)

In [49]:
filter1 = ratings['rating'] > 7
print(filter1)
filter1.any()

0           False
1           False
2           False
3           False
4           False
            ...
20000258    False
20000259    False
20000260    False
20000261    False
20000262    False
Name: rating, Length: 20000263, dtype: bool

np.False_

In [51]:
movies.describe()

             movieId
count   27278.000000
mean    59855.480570
std     44429.314697
min         1.000000
25%      6931.250000
50%     68068.000000
75%    100293.250000
max    131262.000000

In [53]:
movies.head(11)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,11,"American President, The (1995)",Comedy|Drama|Romance